# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ce6a2aacf6c6e73b533ce34ff8022a755f25bbc25986cb980013495b8978618818bfe3d6b6b634d27dd024e5d87defb905d378a051ea9c889dd583ceb2ceef

test:
  secret_key_base: 74ae543e7dec6c2993db31386a6ec07fdabfde19dd4c93c4062c63deb685b49c3f3e9ac2dc6ea22ac0fce58e2f61f2f70a3bf98dfe3f07b5a7876c9cc278681c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
